version: '3.8'

services:
  app:
    build: .
    container_name: sarc-app
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:postgresql://postgres:5432/sarc
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      SERVER_PORT: 8080
    networks:
      - sarc-network
    restart: always

  postgres:
    image: postgres:13
    container_name: sarc-postgres
    environment:
      POSTGRES_DB: sarc
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - sarc-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always

networks:
  sarc-network:
    driver: bridge

volumes:
  postgres-data: