name: Test

on:
  push:
    branches: [ master, development ]
  pull_request:
    branches: [ master, development ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_DB: sarc
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        
      - name: Configurar JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: maven

      - name: Verificar variáveis de ambiente
        run: |
          echo "Verificando variáveis de ambiente disponíveis"
          env | sort

      - name: Criar arquivo .env para testes
        run: |
          echo "# Configurações do banco de dados" > .env
          echo "DB_HOST=localhost" >> .env
          echo "DB_PORT=5432" >> .env
          echo "DB_NAME=sarc" >> .env
          echo "DB_USERNAME=postgres" >> .env
          echo "DB_PASSWORD=postgres" >> .env
          echo "DB_URL=jdbc:postgresql://localhost:5432/sarc" >> .env
          echo "SERVER_PORT=8080" >> .env
          echo "LOGGING_LEVEL_ORG_SPRINGFRAMEWORK=DEBUG" >> .env
          echo "LOGGING_LEVEL_ORG_HIBERNATE=DEBUG" >> .env
          cat .env

      - name: Verificar conexão com PostgreSQL
        run: |
          sudo apt-get update
          sudo apt-get install -y postgresql-client
          PGPASSWORD=postgres psql -h localhost -U postgres -d sarc -c "SELECT 'Conexão bem-sucedida';"

      - name: Mostrar informações do Maven
        run: mvn --version

      - name: Limpar e Empacotar com Maven (sem testes)
        run: mvn clean package -DskipTests

      - name: Executar testes
        run: mvn test
        env:
          DB_URL: jdbc:postgresql://localhost:5432/sarc
          DB_USERNAME: postgres
          DB_PASSWORD: postgres
          SPRING_PROFILES_ACTIVE: test

      - name: Verificar logs em caso de falha
        if: ${{ failure() }}
        run: |
          echo "Verificando logs para diagnóstico de falha..."
          cat target/surefire-reports/*.txt || echo "Sem logs de teste disponíveis."

      - name: Publicar relatórios de teste
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: target/surefire-reports/