name: Test

on:
  push:
    branches: [ master, development ]
  pull_request:
    branches: [ master, development ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    - name: Instalar Docker Compose
      run: |
        sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose
        docker-compose --version

    - name: Subir serviços com Docker Compose
      run: |
        docker-compose -f docker-compose.yml up --build -d
        docker-compose -f docker-compose.yml ps

    - name: Set up PostgreSQL
      uses: harmon758/postgresql-action@v1.0.0
      with:
        postgresqlVersion: '13'
        postgresqlUser: postgres
        postgresqlPassword: postgres
        postgresqlDb: sarc

    - name: Run Tests
      run: mvn -B test -Dspring.profiles.active=test

    - name: Generate Test Report
      if: always()
      run: mvn surefire-report:report-only

    - name: Upload Test Results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-reports
        path: target/site/surefire-report.html
