name: Test

on:
  push:
    branches: [ master, development ]
  pull_request:
    branches: [ master, development ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    
    - name: Set up PostgreSQL
      uses: harmon758/postgresql-action@v1.0.0
      with:
        postgresql version: '13'
        postgresql user: postgres
        postgresql password: postgres
        postgresql db: sarc

    - name: Run Tests
      run: mvn -B test
    
    - name: Generate Test Report
      if: always()
      run: mvn surefire-report:report-only
    
    - name: Upload Test Results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-reports
        path: target/site/surefire-report.html